# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

- name: Ensure Avahi Server is not installed (CIS)
  become: true
  ansible.builtin.package:
    name:
      - 'avahi'
      - 'avahi-autoipd'
    state: absent
